In [34]:
#IT PROVIDE THE FUNCTION TO LOAD THE FILE FROM EXCELA ND MANY MORE 
import pandas

In [35]:
#STORED THE DATA IN DB BY LOADING THE FUNCTION WITH PANDAS
db=pandas.read_csv("dataset.csv")

In [36]:
#DISPLAY db
db

name  hrs  marks
0  vimal    7     70
1  rahul    5     50
2   eric    8     80
3  harry    2     20

In [37]:
#Creating the target that we want to predict.
y=db["marks"]

In [38]:
y

0    70
1    50
2    80
3    20
Name: marks, dtype: int64

In [39]:
#Creating the feature or we can say Independent Variable
x=db["hrs"]

In [40]:
x

0    7
1    5
2    8
3    2
Name: hrs, dtype: int64

In [41]:
#Module that help us to run the the LinerRegression .
#We have used the from keyword beacuse it will not import all the function of sklearn so we will save the memory 
from sklearn.linear_model import LinearRegression

In [42]:
#Creating the mind 
mind=LinearRegression()

In [43]:
#Seeing the Dimension if (,) means 1-d
x.shape

(4,)

In [44]:
#type of x
type(x)

pandas.core.series.Series

In [45]:
#Convert pandas to the numpy array
x=x.values

In [46]:
#See the data Type
type(x)

numpy.ndarray

In [47]:
#Reshape is the function which is used to convert 1-d to many D or many D to 1-D
#Here it is coverting 1-D to 2-D 
x=x.reshape(-1,1)

In [48]:
#tell the shape of the x
x.shape

(4, 1)

In [49]:
#creating the model and fitting the value by this only we will predict one of the very important task in Ml world
model=mind.fit(x,y)

In [50]:
#Predict the value that we want 
model.predict([[7]])

array([70.])

In [51]:
model.predict([[5]])

array([50.])

In [52]:
#it will tell the value of the w or c or we can say cofficient value
model.coef_

array([10.])

In [53]:
#By this Library we can Store the data in hard_Disk
#and we can use in the prog.any where 
import joblib

In [54]:
#save the trained model in the file marks.pkj
joblib.dump(mind,"marks.pkj")

['marks.pkj']