In [105]:
import pandas
import numpy

In [106]:
dataset=pandas.read_csv("50_Startups.csv")

In [107]:
dataset.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [108]:
dataset.columns


Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [109]:
State=dataset["State"]

In [110]:
#Lable Encoding Done Start here
from sklearn.preprocessing import LabelEncoder

In [111]:
State_le=LabelEncoder()

In [112]:
State_le_final=State_le.fit_transform(State).reshape(-1,1)

In [113]:
#From Here we Start ONEHOTENCODNG
from sklearn.preprocessing import OneHotEncoder

In [114]:
State_OHE=OneHotEncoder()

In [115]:
State_Dump=State_OHE.fit_transform(State_le_final)

In [116]:
State_Dump

<50x3 sparse matrix of type '<class 'numpy.float64'>'
	with 50 stored elements in Compressed Sparse Row format>

In [117]:
#To SEE Dummy Variable 
State_Final=State_Dump.toarray()

In [118]:
#Final data after doing data preProcessng 
State_Final
#LeSt Step of data pre Processiong 

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0

In [119]:
#Here WE are Removing the DummyVariableTrab BY doing this Removing the Last Column
State_Final_Trap=State_Final[: , :2]

In [120]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [121]:
y=dataset["Profit"]

In [122]:
#Storing the value of the of # field
X=dataset[["R&D Spend","Administration","Marketing Spend"]]

In [123]:
#Adding the value of x value with State_Final_trap after all preprocessing of data and add horiziontly 
X=numpy.hstack((X,State_Final_Trap))

In [124]:
#creating a linear model
from sklearn.linear_model import LinearRegression

In [125]:
#Split The Data for test and train 
from sklearn.model_selection import train_test_split

In [126]:
#Dividing the data into 2 part for test and train. test size is of 20%
    X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.20, random_state=42)

In [127]:
X_test.shape

(10, 5)

In [128]:
X_train.shape

(40, 5)

In [129]:
#Fitting the model 
model.fit(X_train,y_train)

LinearRegression()

In [132]:
#Predict theall the 20% of the x_train
model.predict(X_test)

array([126362.87908254,  84608.45383635,  99677.49425148,  46357.46068582,
       128750.48288503,  50912.41741885, 109741.35032702, 100643.24281646,
        97599.27574595, 113097.42524433])

In [133]:
model.coef_

array([ 8.05630064e-01, -6.87878823e-02,  2.98554429e-02, -6.98775997e+00,
        9.31805246e+02])